### ISSUE TITLE
Bewitchment opal dissapear

### ISSUE THREAD

**Issue by Basch** [teibidhio/HereThereBe#3]
Every time i get an opal in my inventory, it dissapear after closing it.

**Comment by Teibidh** [comment]
Are you running unifier or anything else that automatically changes ore
dicted items that match to the same type? I found the ore dictionary
"gemAll" to be the culprit.

**Comment by Basch** [comment]
The problem was coming from unifier.
Solution :
Add `bewitchment:opal` in disallowedIds list of unfifier conf file.
 Thanks

**Comment by Teibidh** [comment]
I put "gemAll" in the denied prefix list for unifier instead. I had the
same problem with garnet and amethyst
