### ISSUE TITLE
Thaumcraft soap seems to not work

### ISSUE THREAD

**Issue by Basch** [teibidhio/HereThereBe#4]
Some players of my server are invested into thaumcraft but they told me soap doesn't seem to clean temporary warp.

**Comment by Teibidh** [comment]
There are actually a handful of things in Thaumcraft that aren't working correctly. Consequently it has been removed from the most recent version of the pack.

As an extreme example, and one of the primary drivers behind the decision, there are places in TC progression that you cannot pass through if you have progressed in any of the fire resistance options the pack provides.
